controller_list:
  - name: yaren_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
      - Joint_7
      - Joint_8
      - Joint_9
      - Joint_10
      - Joint_11
      - Joint_12